name: Bug Report
description: Report a bug or unexpected behavior in earthcast-mcp
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What went wrong? Be as specific as possible.
      placeholder: Describe the bug clearly and concisely
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Configure MCP client with...
        2. Run command or query...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if applicable.
      placeholder: Paste any error messages, stack traces, or unexpected output
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: earthcast-mcp Version
      description: What version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      options:
        - Claude Desktop
        - Warp
        - Cursor
        - Cline (VS Code)
        - Claude Code (CLI)
        - Grok (xAI)
        - Other
    validations:
      required: true

  - type: dropdown
    id: api
    attributes:
      label: Which API is affected?
      description: Which part of the system is having issues?
      options:
        - Earthcast Technologies API
        - NOAA Weather API
        - Open-Meteo API
        - Other weather APIs
        - Not sure
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version` to find this
      placeholder: "v18.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Configuration details, screenshots, related issues, etc.
    validations:
      required: false
